{
    "name": "TRMNL",
    "summary": "Module for TRMNL display management",
    "description": "Manage devices, profiles, and render logs for TRMNL",
    "category": "Productivity / IoT",
    "author": "Abilium GmbH",
    "license": "Other OSI approved licence",
    "version": "1.0.1",
    "post_init_hook": "post_init_hook",
    "images": ["static/description/icon.png"],
    "depends": ["base",],
    "external_dependencies": {"python": ["Pillow", "requests"]},
    "data": [
            "security/ir.model.access.csv",
            "views/trmnl_device_views.xml",
            "views/trmnl_device_wizard_views.xml",
            "views/trmnl_profile_views.xml",
            "views/trmnl_menu.xml",
            ],
}
